### ISSUE TITLE
Add support for resuming playback

### ISSUE THREAD

**Issue by RobertMe** [mzanetti/kodimote#14]
I have (an old) branch to support resume. But there were some issues with our implementation for starting playback*. So I'd need to investigate how to finish that branch so we finally have support for resuming.

* Currently playing an item involves the following:
1. Clear the playlist
2. Add the item (song, episode, movie) to the playlist
3. Start playing the playlist
But XBMC (and Kodi?) don't support resuming playback in a playlist.

**Comment by RobertMe** [comment]
@mzanetti do you remember why the implementation is as it is? Why work with the playlist, instead of starting to play the item directly (which does support resume)?

**Comment by mzanetti** [comment]
The reason is that Kodi does that if you click enter on an item in you library. So I wanted to keep that behavior the same. I just saw that Kodi doesn't do that consistently though, for example if you open a tv show from the recently added thumbnails above the main menu it just does the Open() thing. Resuming playback from the saved position is probably more valuable than playlists for tvshows. So let's change it to call open for movies and tv shows, keeping the playlist behavior for music.

**Comment by RobertMe** [comment]
Yep, as discussed last week.

IIRC my current implementation was still a bit broken, but didn't invest too much time in it afterwards. I'm ok with keeping this issue open until till after the first Kodimote release. As there haven't been any requests for it, although it definitely is a feature which should be supported rather sooner than later.
