### ISSUE TITLE
Add optional "buttons pad"

### ISSUE THREAD

**Issue by RobertMe** [mzanetti/kodimote#20]
In Jolla Harbour there are some requests to have buttons instead of the gesturepad. So I would like to add an optional "buttons pad" which the user can select from the settings.

**Comment by mzanetti** [comment]
I still believe the current gesture pad is superior for the following reasons:
* One can use it to navigate kodi without having to look down to the phone because interaction elements use the maximum available space.
* It can do scrolling through long lists allowing the user to adjust the speed of the scrolling

Also I've done various attempts to come up with a usable button based keypad in the early days of xbmcremote.

I think the issue is that people try to click on it and wonder why it only does OK presses. I've added an intro tutorial now: http://notyetthere.org/data/gestures-intro.ogv
Let's see how that works out. Even if we should decide at some later point to add a button based pad, this intro might be a good idea anyways because especially the scrolling is indeed not very discoverable.

**Comment by RobertMe** [comment]
Closing. Let's hope #29 is good enough. Otherwise I'll reopen/recreate.
