### ISSUE TITLE
Keypad doesn't work

### ISSUE THREAD

**Issue by carmenfdezb** [mzanetti/kodimote#47]
The controlpad doesn't work (when I click on any direction, nothing happens).
And it doesn't display any icons.

**Comment by RobertMe** [comment]
Hi, on which platform is this? Ubuntu or Sailfish?

And do you see the intro texts, or just empty blocks were the buttons should be? So does it look like this video: http://notyetthere.org/data/gestures-intro.ogv (which is of Ubuntu, but Sailfish looks about the same, and it's a bit outdated).

If I'm not mistaken these are the steps to finish the intro:
1. horizontal arrows are flashing, which means you'd have to swipe left or right
2. vertical arrows are flashing, to swipe up or down
3. down arrows are flashing, to hint you'd can hold the swipe for a longer period of time, as a "button repeat" (you'd need to click 10 times)
4. all arrows are flashing, meaning you'd have to enter (just click on the pad)
5. the color buttons appear, all arrows keep flashing, click the gesture pad once again to finish the intro

**Comment by carmenfdezb** [comment]
I'm using Sailfish, I've installed your app in my Jolla Phone. I've made two screenshots:
![20150203211640](https://cloud.githubusercontent.com/assets/6286776/6028772/3271f484-abec-11e4-8b82-23efd28f3fb2.jpg)
![20150203211700](https://cloud.githubusercontent.com/assets/6286776/6028773/350b54ce-abec-11e4-9e6a-fe2f30b7d208.jpg)
If I swipe left or right, up or down, nothing happens
I was using Xbmcremote, and with this app the keypad had worked fine

**Comment by RobertMe** [comment]
Ok, thanks. This confirms what @mzanetti and I were thinking already. In this "introduction step" we'll try(but fail) to teach you that you can keep scrolling by holding the gesture. If you press and swipe down (or any other direction) it will send that keypress once, but when you keep holding (after starting the swipe), the keypress will be repeated. So you'll need to press on the gesture pad (preferably in the middle), swipe down (till the edge of the pad/diamond shape), and then keep holding, after a while it will then go to the next step (after "sending" 10 directional key presses).

So thanks for confirming this is the issue. We've tried to improve the experience of using the gesture pad by explaining how it can be used (because of previous complaints about not using buttons). But as you've just confirmed, this isn't the way to go. So if you have any tips on how to improve this introduction I'm glad to know.

I also think I'll need to improve the gesture pad (for Harbour users). When using the OpenRepos/Warehouse version (or the Ubuntu one, or the one for MeeGo) the phone will vibrate when you either click (enter), swipe (go left/right/...), or hold and swipe (left/right/... with key repeat, the step which you're currently stuck on), so the app confirms it's doing something then. But for Harbour apps it isn't allowed to vibrate, so you get no confirmation something is actually happening.

@mzanetti I'm also thinking about lowering the number of presses you need to send, to say 5 or so, and maybe updating one of the two texts. So it's something like "Keep holding to keep going <chosen direction>". And we might want to cancel/finish the introduction when the user closes (/reopens) the page, so he can't get stuck. If he doesn't finish the introduction, closes the page, and then comes back, everything should be working as normal. Instead of forcing the user to go through all these hoops to get a working keypad.

**Comment by mzanetti** [comment]
I think the main issue issue is that you need to press and hold for a bit, and only then start dragging. Will fix that. Once the scroll mode is activated, I don't think it makes much of a difference if it's triggered 5 or 10 times as it will count up pretty fast. It's really about the activating scroll mode. The reason why I chose 10 times is to give the user enough time to realize that dragging further improves the frequency. However, Harbor lacking support for haprics feedback is a real issue with that... Do you think a visual feedback (like the gesture pad glowing up) would help as a workaround?

Once the drag mode detection is fixed, everyone should be able to complete the intro so I don't think cancelling the intro is the best option.

Changing some of the text might be useful, probably adding a fullscreen overlay/dialog in the beginning that tells the user that this is a short tutorial to show how to use the gestures and that [s]he should follow a few steps before actually using it. That one wiould be especially useful for people that have previously been using xbmcremote already and might don't expect to see an intro at this point (like in this case).

**Comment by carmenfdezb** [comment]
I don't know what I did, but now keypad is working fine. However, I think it's not very intuitive.
Thank you for help me.

**Comment by RobertMe** [comment]
> Do you think a visual feedback (like the gesture pad glowing up) would help as a workaround?

I thought about highlighting the arrows (of the direction you're swiping in), but then I saw that's already the case. So we might want to try something else (highlighting the full pad/diamond shape).

> Changing some of the text might be useful

Yep, we should definitely add a hint to keep holding after activating the "key repeat"

> probably adding a fullscreen overlay/dialog in the beginning

IMHO that would be a dialog, which the user can cancel to use the keypad without finishing the intro

But there also seem to be some other issues:
1. In this step (keep swiping) the step is erroneously finished when you only keep holding, you don't have to move
2. When you start the swipe at the edge of the pad, and then swipe to outside the pad, before the "onPressAndHold" signal is emited, the signal won't be triggered. So we might want to add a manual timer which we start when "onPressed" is emited, and start the repeat timer when the first timer finishes, instead of relying on "onPressAndHold"
